SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte(
        IdCompte   Int  NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
        Pseudo     Varchar (25) NOT NULL ,
        MotDePasse Varchar (25) NOT NULL ,
        Email      Varchar (25) NOT NULL ,
        Prenom     Varchar (25) NOT NULL ,
        Nom        Varchar (25) NOT NULL ,
        Credit     Int NOT NULL
	,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE produit(
        IdProduit   Int NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
        Photo       Varchar (300) NOT NULL ,
        Description Varchar (300) NOT NULL ,
        PrixMinimal Int NOT NULL ,
        DateDebut   Varchar (10) NOT NULL ,
        DateFin     Varchar (10) NOT NULL ,
        HeureDebut  Varchar (8) NOT NULL ,
        HeureFin    Varchar (8) NOT NULL ,
        Flag        Bool NOT NULL ,
        IdCompte    Int NOT NULL
	,PRIMARY KEY (IdProduit)

	,FOREIGN KEY (IdCompte) REFERENCES compte(IdCompte)
);

CREATE TABLE mouvement(
        IdMouvement Int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        Somme       FLOAT8
        NOT NULL ,
        IdCompte    Int NOT NULL
	,PRIMARY KEY (IdMouvement)

	,FOREIGN KEY (IdCompte) REFERENCES compte(IdCompte)
);

CREATE TABLE enchere(
        IdEnchere Int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        Prix      Int NOT NULL ,
        IdProduit Int NOT NULL ,
        IdCompte  Int NOT NULL
	,PRIMARY KEY (IdEnchere)

	,FOREIGN KEY (IdProduit) REFERENCES produit(IdProduit)
	,FOREIGN KEY (IdCompte) REFERENCES compte(IdCompte)
);

